# Generated by Django 5.2.17 on 2026-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('fan', 'Subjects'), ('kasb', 'Careers')], default='fan', max_length=10),
        ),
    ]
